var EmployeeData = {
    Rows: [
        {
            "__status": null,
            "ID": 1,
            "DepartmentID": 3,
            "RealName": "fewf",
            "DepartmentName": "销售部",
            "Sex": 1,
            "Age": 2433,
            "IncomeDay": "2011-5-2",
            "Phone": "159244332",
            "Address": "变为不为恶"
        },
        {
            "__status": null,
            "ID": 2,
            "DepartmentID": 1,
            "RealName": "李三34",
            "DepartmentName": "主席",
            "Sex": 2,
            "Age": 23,
            "IncomeDay": "2012-1-2",
            "Phone": "2323232323",
            "Address": "3434"
        },
        {
            "__status": null,
            "ID": 3,
            "DepartmentID": 3,
            "RealName": "吴彬3",
            "DepartmentName": "销售部",
            "Sex": 2,
            "Age": 26,
            "IncomeDay": "2011-5-2",
            "Phone": "159244332",
            "Address": "1311飞屋服务费3434343433434"
        },
        {
            "__status": null,
            "ID": 5,
            "DepartmentID": 2,
            "RealName": "吴久",
            "DepartmentName": "研发中心",
            "Sex": 2,
            "Age": 29,
            "IncomeDay": "2012-5-2",
            "Phone": "159244332",
            "Address": "3444444"
        },
        {
            "__status": null,
            "ID": 6,
            "DepartmentID": 3,
            "RealName": "陈民",
            "DepartmentName": "销售部",
            "Sex": 2,
            "Age": 21,
            "IncomeDay": "2014-1-1",
            "Phone": null,
            "Address": "3435333"
        },
        {
            "__status": null,
            "ID": 7,
            "DepartmentID": 3,
            "RealName": "陈留",
            "DepartmentName": "销售部",
            "Sex": 1,
            "Age": 32,
            "IncomeDay": "2013-5-6",
            "Phone": null,
            "Address": "3333444444444444"
        },
        {
            "__status": null,
            "ID": 8,
            "DepartmentID": 1,
            "RealName": "谢银223",
            "DepartmentName": "主席",
            "Sex": 1,
            "Age": 13,
            "IncomeDay": "2011-1-2",
            "Phone": null,
            "Address": "34344555555555"
        },
        {
            "__status": null,
            "ID": 10,
            "DepartmentID": 2,
            "RealName": "陈元为2",
            "DepartmentName": "研发中心",
            "Sex": 2,
            "Age": 16,
            "IncomeDay": "2011-6-2",
            "Phone": null,
            "Address": "34343434343434"
        },
        {
            "__status": null,
            "ID": 11,
            "DepartmentID": 1,
            "RealName": "大为",
            "DepartmentName": "主席",
            "Sex": 1,
            "Age": 19,
            "IncomeDay": "2014-5-2",
            "Phone": null,
            "Address": "3434444444"
        },
        {
            "__status": null,
            "ID": 21,
            "DepartmentID": 4,
            "RealName": "444",
            "DepartmentName": "市场部",
            "Sex": 2,
            "Age": 20,
            "IncomeDay": "2014-5-2",
            "Phone": null,
            "Address": "444"
        },
        {
            "__status": null,
            "ID": 22,
            "DepartmentID": 1,
            "RealName": "22",
            "DepartmentName": "主席",
            "Sex": 1,
            "Age": 20,
            "IncomeDay": "2012-5-2",
            "Phone": null,
            "Address": "22"
        },
        {
            "__status": null,
            "ID": 23,
            "DepartmentID": 2,
            "RealName": "22",
            "DepartmentName": "研发中心",
            "Sex": 1,
            "Age": 20,
            "IncomeDay": "2014-5-1",
            "Phone": null,
            "Address": "2224444444"
        },
        {
            "__status": null,
            "ID": 26,
            "DepartmentID": 4,
            "RealName": "232323",
            "DepartmentName": "市场部",
            "Sex": 2,
            "Age": 0,
            "IncomeDay": "2014-5-2",
            "Phone": null,
            "Address": "222222222222222"
        }
    ],
    Total: 13
};